import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "../../styles/globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
